use_frameworks!

target 'CresenityIOS_Example' do
  pod 'CresenityIOS', :path => '../'

  target 'CresenityIOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
